artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/ac4a7bf00edb4a7e80548e564844a972/artifacts
end_time: 1742980285590
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: ac4a7bf00edb4a7e80548e564844a972
run_name: CV_elastincnet
run_uuid: ac4a7bf00edb4a7e80548e564844a972
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980285571
status: 3
tags: []
user_id: remicazelles
