artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/ddbaf9f433534b4aa1c5d7a62ffe3922/artifacts
end_time: 1742389658842
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: ddbaf9f433534b4aa1c5d7a62ffe3922
run_name: CV_elastincnet
run_uuid: ddbaf9f433534b4aa1c5d7a62ffe3922
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389658824
status: 3
tags: []
user_id: remicazelles
