artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/b9d33ff006a74a579ad49d0c9f7fb28e/artifacts
end_time: 1742980281520
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: b9d33ff006a74a579ad49d0c9f7fb28e
run_name: CV_elastincnet
run_uuid: b9d33ff006a74a579ad49d0c9f7fb28e
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980281503
status: 3
tags: []
user_id: remicazelles
