artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/edc34e873c3547d39f0ae564a30a7c8c/artifacts
end_time: 1742389663187
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: edc34e873c3547d39f0ae564a30a7c8c
run_name: CV_elastincnet
run_uuid: edc34e873c3547d39f0ae564a30a7c8c
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389663170
status: 3
tags: []
user_id: remicazelles
