artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/2a152ea56be448ad8634a34d800eed33/artifacts
end_time: 1742031705849
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: 2a152ea56be448ad8634a34d800eed33
run_name: CV_elastincnet
run_uuid: 2a152ea56be448ad8634a34d800eed33
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031705837
status: 3
tags: []
user_id: remicazelles
