artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/e2363ce6f99c4ddfa528ea14f38ba167/artifacts
end_time: 1742980285482
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: e2363ce6f99c4ddfa528ea14f38ba167
run_name: CV_elastincnet
run_uuid: e2363ce6f99c4ddfa528ea14f38ba167
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980285461
status: 3
tags: []
user_id: remicazelles
