artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/26c28b5a78864670b2f2e8aa5b6d2f79/artifacts
end_time: 1742389664277
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 26c28b5a78864670b2f2e8aa5b6d2f79
run_name: CV_elastincnet
run_uuid: 26c28b5a78864670b2f2e8aa5b6d2f79
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389664261
status: 3
tags: []
user_id: remicazelles
