artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/61e62c92a5884aa4a7dae3f95a5a70d3/artifacts
end_time: 1742032545858
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: 61e62c92a5884aa4a7dae3f95a5a70d3
run_name: CV_elastincnet
run_uuid: 61e62c92a5884aa4a7dae3f95a5a70d3
source_name: ''
source_type: 4
source_version: ''
start_time: 1742032545843
status: 3
tags: []
user_id: remicazelles
