artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/b1ddaa20d0c744fda3e59dcf841409ea/artifacts
end_time: 1742389660149
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: b1ddaa20d0c744fda3e59dcf841409ea
run_name: CV_elastincnet
run_uuid: b1ddaa20d0c744fda3e59dcf841409ea
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389660135
status: 3
tags: []
user_id: remicazelles
