artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/f0e5d9eb84734e2f80879ae1ea886d3a/artifacts
end_time: 1742980281701
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: f0e5d9eb84734e2f80879ae1ea886d3a
run_name: CV_elastincnet
run_uuid: f0e5d9eb84734e2f80879ae1ea886d3a
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980281683
status: 3
tags: []
user_id: remicazelles
