artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/89782b2e744746f1afe9c8dede0dc7c5/artifacts
end_time: 1742980286169
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 89782b2e744746f1afe9c8dede0dc7c5
run_name: CV_elastincnet
run_uuid: 89782b2e744746f1afe9c8dede0dc7c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980286150
status: 3
tags: []
user_id: remicazelles
