artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070/e8da0a44c65548de80bf6bde9e9c7692/artifacts
end_time: 1746454410892
entry_point_name: ''
experiment_id: '341922289666668070'
lifecycle_stage: active
run_id: e8da0a44c65548de80bf6bde9e9c7692
run_name: whimsical-squid-387
run_uuid: e8da0a44c65548de80bf6bde9e9c7692
source_name: ''
source_type: 4
source_version: ''
start_time: 1746454410543
status: 3
tags: []
user_id: remicazelles
