artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/7c5bcb4008954f37aa47173eecc04a4c/artifacts
end_time: 1742980279508
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 7c5bcb4008954f37aa47173eecc04a4c
run_name: CV_elastincnet
run_uuid: 7c5bcb4008954f37aa47173eecc04a4c
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980279491
status: 3
tags: []
user_id: remicazelles
