artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/38d02b636b394d48abdea95c8dd9990d/artifacts
end_time: 1742389665194
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 38d02b636b394d48abdea95c8dd9990d
run_name: CV_elastincnet
run_uuid: 38d02b636b394d48abdea95c8dd9990d
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389665177
status: 3
tags: []
user_id: remicazelles
