artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/e52e4fb4a86a4c0bbc90fa158c151976/artifacts
end_time: 1742980278998
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: e52e4fb4a86a4c0bbc90fa158c151976
run_name: CV_elastincnet
run_uuid: e52e4fb4a86a4c0bbc90fa158c151976
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980278981
status: 3
tags: []
user_id: remicazelles
