aliases: []
creation_timestamp: 1742993064787
current_stage: None
description: ''
last_updated_timestamp: 1742993064787
name: best_elasticnet_model_on_2025-03-26
run_id: ee8a6b3c9de444ae88148199b31d088d
run_link: ''
source: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/0/ee8a6b3c9de444ae88148199b31d088d/artifacts/logged_model
status: READY
status_message: null
storage_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/0/ee8a6b3c9de444ae88148199b31d088d/artifacts/logged_model
user_id: null
version: 6
