artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/161233834943891904/9283b1d4ced347ca885b2badc7c49f39/artifacts
end_time: 1742389667043
entry_point_name: ''
experiment_id: '161233834943891904'
lifecycle_stage: active
run_id: 9283b1d4ced347ca885b2badc7c49f39
run_name: CrossValidate_elasticnet
run_uuid: 9283b1d4ced347ca885b2badc7c49f39
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389666923
status: 3
tags: []
user_id: remicazelles
