artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/e57955b991e04acbbceb5bc69405b577/artifacts
end_time: 1742389661799
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: e57955b991e04acbbceb5bc69405b577
run_name: CV_elastincnet
run_uuid: e57955b991e04acbbceb5bc69405b577
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389661783
status: 3
tags: []
user_id: remicazelles
