artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/d4bd247e87b34e56b7ee6b48979a2877/artifacts
end_time: 1742389666509
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: d4bd247e87b34e56b7ee6b48979a2877
run_name: CV_elastincnet
run_uuid: d4bd247e87b34e56b7ee6b48979a2877
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389666491
status: 3
tags: []
user_id: remicazelles
