artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/dc5f4d730c024b439ddac5d5e01745cc/artifacts
end_time: 1742389663358
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: dc5f4d730c024b439ddac5d5e01745cc
run_name: CV_elastincnet
run_uuid: dc5f4d730c024b439ddac5d5e01745cc
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389663341
status: 3
tags: []
user_id: remicazelles
