artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/517828280626744178/b2a8728eb5484100bede5ff9770e2d3e/artifacts
end_time: 1742388900489
entry_point_name: ''
experiment_id: '517828280626744178'
lifecycle_stage: active
run_id: b2a8728eb5484100bede5ff9770e2d3e
run_name: victorious-toad-679
run_uuid: b2a8728eb5484100bede5ff9770e2d3e
source_name: ''
source_type: 4
source_version: ''
start_time: 1742388900409
status: 3
tags: []
user_id: remicazelles
