artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/fe43dac6c006488495cc6e2ae5b37012/artifacts
end_time: 1742032134681
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: fe43dac6c006488495cc6e2ae5b37012
run_name: CV_elastincnet
run_uuid: fe43dac6c006488495cc6e2ae5b37012
source_name: ''
source_type: 4
source_version: ''
start_time: 1742032134668
status: 3
tags: []
user_id: remicazelles
