artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/70e6a8f457d5434c9e52c3d62ed9e0ce/artifacts
end_time: 1742032545634
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: 70e6a8f457d5434c9e52c3d62ed9e0ce
run_name: CV_elastincnet
run_uuid: 70e6a8f457d5434c9e52c3d62ed9e0ce
source_name: ''
source_type: 4
source_version: ''
start_time: 1742032545621
status: 3
tags: []
user_id: remicazelles
