artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070/e1e9e4fed49d4f5092c59d0ae7c88a10/artifacts
end_time: 1746454408443
entry_point_name: ''
experiment_id: '341922289666668070'
lifecycle_stage: active
run_id: e1e9e4fed49d4f5092c59d0ae7c88a10
run_name: amazing-mink-966
run_uuid: e1e9e4fed49d4f5092c59d0ae7c88a10
source_name: ''
source_type: 4
source_version: ''
start_time: 1746454408278
status: 3
tags: []
user_id: remicazelles
