artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/0/b55185ee1bd04934999097be1fadfa17/artifacts
end_time: 1742996130356
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b55185ee1bd04934999097be1fadfa17
run_name: 2025-03-26_elasticnet_best_model_run
run_uuid: b55185ee1bd04934999097be1fadfa17
source_name: ''
source_type: 4
source_version: ''
start_time: 1742996127472
status: 3
tags: []
user_id: remicazelles
