artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/c8a573fed4dd4b92bee2a076181dd2f4/artifacts
end_time: 1742389662920
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: c8a573fed4dd4b92bee2a076181dd2f4
run_name: CV_elastincnet
run_uuid: c8a573fed4dd4b92bee2a076181dd2f4
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389662904
status: 3
tags: []
user_id: remicazelles
