artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/380618932535725939/a72de821ef5e47c0ac840c3ec5d388ba/artifacts
end_time: 1742980117434
entry_point_name: ''
experiment_id: '380618932535725939'
lifecycle_stage: active
run_id: a72de821ef5e47c0ac840c3ec5d388ba
run_name: bustling-moth-362
run_uuid: a72de821ef5e47c0ac840c3ec5d388ba
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980117362
status: 3
tags: []
user_id: remicazelles
