artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/d0d79c4f894149afa5900802f6fdc5ba/artifacts
end_time: 1742389664119
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: d0d79c4f894149afa5900802f6fdc5ba
run_name: CV_elastincnet
run_uuid: d0d79c4f894149afa5900802f6fdc5ba
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389664101
status: 3
tags: []
user_id: remicazelles
