artifact_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/622210678106996608
creation_time: 1742031653153
experiment_id: '622210678106996608'
last_update_time: 1742031653153
lifecycle_stage: active
name: /2025-03-15_Tune_model_and_log
