artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/17efe38f564d494d974dfdf62f0ba4d9/artifacts
end_time: 1742980286142
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 17efe38f564d494d974dfdf62f0ba4d9
run_name: CV_elastincnet
run_uuid: 17efe38f564d494d974dfdf62f0ba4d9
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980286123
status: 3
tags: []
user_id: remicazelles
