aliases: []
creation_timestamp: 1742389504022
current_stage: None
description: ''
last_updated_timestamp: 1742389504022
name: best_elasticnet_model_on_2025-03-19
run_id: 4cb4bf4042cb44698b76b8afa248b422
run_link: ''
source: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/161233834943891904/4cb4bf4042cb44698b76b8afa248b422/artifacts/logged_model
status: READY
status_message: null
storage_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/161233834943891904/4cb4bf4042cb44698b76b8afa248b422/artifacts/logged_model
user_id: null
version: 1
