artifact_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293
creation_time: 1742980277372
experiment_id: '740126467069218293'
last_update_time: 1742980277372
lifecycle_stage: active
name: 2025-03-26_ElasticNetCV_hyperparams_search
