artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070/77a5b68e241149cf9cbce950bad91a37/artifacts
end_time: 1746454409592
entry_point_name: ''
experiment_id: '341922289666668070'
lifecycle_stage: active
run_id: 77a5b68e241149cf9cbce950bad91a37
run_name: gregarious-ant-698
run_uuid: 77a5b68e241149cf9cbce950bad91a37
source_name: ''
source_type: 4
source_version: ''
start_time: 1746454409517
status: 3
tags: []
user_id: remicazelles
