artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/b3c4c8d25d7d43cf97ea7ef59648974a/artifacts
end_time: 1742031652595
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: b3c4c8d25d7d43cf97ea7ef59648974a
run_name: CV_elastincnet
run_uuid: b3c4c8d25d7d43cf97ea7ef59648974a
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031652582
status: 3
tags: []
user_id: remicazelles
