artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/aefbe95feb0f4589b9193e1951c86bbc/artifacts
end_time: 1742389660607
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: aefbe95feb0f4589b9193e1951c86bbc
run_name: CV_elastincnet
run_uuid: aefbe95feb0f4589b9193e1951c86bbc
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389660591
status: 3
tags: []
user_id: remicazelles
