artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/ce28ac308c974691ab4f4f96623fb3d9/artifacts
end_time: 1742980286425
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: ce28ac308c974691ab4f4f96623fb3d9
run_name: CV_elastincnet
run_uuid: ce28ac308c974691ab4f4f96623fb3d9
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980286406
status: 3
tags: []
user_id: remicazelles
