artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070/d53c8a6caee34a7fb2a9d166f06de18a/artifacts
end_time: 1746454408760
entry_point_name: ''
experiment_id: '341922289666668070'
lifecycle_stage: active
run_id: d53c8a6caee34a7fb2a9d166f06de18a
run_name: nosy-mole-747
run_uuid: d53c8a6caee34a7fb2a9d166f06de18a
source_name: ''
source_type: 4
source_version: ''
start_time: 1746454408534
status: 3
tags: []
user_id: remicazelles
