artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/832d0373ce92478f916fddf81be555eb/artifacts
end_time: 1742389665637
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 832d0373ce92478f916fddf81be555eb
run_name: CV_elastincnet
run_uuid: 832d0373ce92478f916fddf81be555eb
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389665620
status: 3
tags: []
user_id: remicazelles
