artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/8411096fb2a14e16a3f6c92a59e469bb/artifacts
end_time: 1742980280555
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 8411096fb2a14e16a3f6c92a59e469bb
run_name: CV_elastincnet
run_uuid: 8411096fb2a14e16a3f6c92a59e469bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980280538
status: 3
tags: []
user_id: remicazelles
