aliases: []
creation_timestamp: 1742032549176
current_stage: None
description: ''
last_updated_timestamp: 1742032549176
name: best_elasticnet_model_on_2025-03-15
run_id: dc7ae6946b33437b98c38447bdd9d140
run_link: ''
source: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/622210678106996608/dc7ae6946b33437b98c38447bdd9d140/artifacts/logged_model
status: READY
status_message: null
storage_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/622210678106996608/dc7ae6946b33437b98c38447bdd9d140/artifacts/logged_model
user_id: null
version: 4
