artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/7d6b08415d074faabb076490fb81bf45/artifacts
end_time: 1742032134641
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: 7d6b08415d074faabb076490fb81bf45
run_name: CV_elastincnet
run_uuid: 7d6b08415d074faabb076490fb81bf45
source_name: ''
source_type: 4
source_version: ''
start_time: 1742032134627
status: 3
tags: []
user_id: remicazelles
