artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/b58d7a6f3348430aa8538b83c8a7a7da/artifacts
end_time: 1742032545369
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: b58d7a6f3348430aa8538b83c8a7a7da
run_name: CV_elastincnet
run_uuid: b58d7a6f3348430aa8538b83c8a7a7da
source_name: ''
source_type: 4
source_version: ''
start_time: 1742032545355
status: 3
tags: []
user_id: remicazelles
