artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/b9052abb6bfe4f27b03e6efe62f8d680/artifacts
end_time: 1742032134389
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: b9052abb6bfe4f27b03e6efe62f8d680
run_name: CV_elastincnet
run_uuid: b9052abb6bfe4f27b03e6efe62f8d680
source_name: ''
source_type: 4
source_version: ''
start_time: 1742032134376
status: 3
tags: []
user_id: remicazelles
