artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/eb86dda8a0d04277abeec3376fe65e58/artifacts
end_time: 1742389665714
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: eb86dda8a0d04277abeec3376fe65e58
run_name: CV_elastincnet
run_uuid: eb86dda8a0d04277abeec3376fe65e58
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389665696
status: 3
tags: []
user_id: remicazelles
