artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/ef7cb883a19e4413bf0398dec28c7972/artifacts
end_time: 1742031705872
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: ef7cb883a19e4413bf0398dec28c7972
run_name: CV_elastincnet
run_uuid: ef7cb883a19e4413bf0398dec28c7972
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031705856
status: 3
tags: []
user_id: remicazelles
