artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/cd0324deaa8f4489a6319e9515da6fa7/artifacts
end_time: 1742389666061
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: cd0324deaa8f4489a6319e9515da6fa7
run_name: CV_elastincnet
run_uuid: cd0324deaa8f4489a6319e9515da6fa7
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389666042
status: 3
tags: []
user_id: remicazelles
