artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/74848f6fce0142d8b7a15fcb94f1ad4a/artifacts
end_time: 1742389662627
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 74848f6fce0142d8b7a15fcb94f1ad4a
run_name: CV_elastincnet
run_uuid: 74848f6fce0142d8b7a15fcb94f1ad4a
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389662611
status: 3
tags: []
user_id: remicazelles
