artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/ff7a4afc45f24851bee7198d8d62faca/artifacts
end_time: 1742389666196
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: ff7a4afc45f24851bee7198d8d62faca
run_name: CV_elastincnet
run_uuid: ff7a4afc45f24851bee7198d8d62faca
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389666179
status: 3
tags: []
user_id: remicazelles
