artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/fd67dced7b4a4773820f06ea5d210a74/artifacts
end_time: 1742389661650
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: fd67dced7b4a4773820f06ea5d210a74
run_name: CV_elastincnet
run_uuid: fd67dced7b4a4773820f06ea5d210a74
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389661631
status: 3
tags: []
user_id: remicazelles
