artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/380618932535725939/1d627db24fb54c7daf25b9e07462e271/artifacts
end_time: 1742980118589
entry_point_name: ''
experiment_id: '380618932535725939'
lifecycle_stage: active
run_id: 1d627db24fb54c7daf25b9e07462e271
run_name: classy-sloth-552
run_uuid: 1d627db24fb54c7daf25b9e07462e271
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980114715
status: 3
tags: []
user_id: remicazelles
