artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/32f92b4744be4eaaa9cd344f42f70fb3/artifacts
end_time: 1742980280954
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 32f92b4744be4eaaa9cd344f42f70fb3
run_name: CV_elastincnet
run_uuid: 32f92b4744be4eaaa9cd344f42f70fb3
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980280936
status: 3
tags: []
user_id: remicazelles
