artifact_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/517828280626744178
creation_time: 1742388897673
experiment_id: '517828280626744178'
last_update_time: 1742388897673
lifecycle_stage: active
name: /2025-03-19Carbon_waters_Saving_pipeline_linear_model
