artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/8a30b24115d240e094aa9f7ac20c432f/artifacts
end_time: 1742389663140
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 8a30b24115d240e094aa9f7ac20c432f
run_name: CV_elastincnet
run_uuid: 8a30b24115d240e094aa9f7ac20c432f
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389663123
status: 3
tags: []
user_id: remicazelles
