artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/380618932535725939/fe8e0f775efc4c9aabd5f845424d3061/artifacts
end_time: 1742980115600
entry_point_name: ''
experiment_id: '380618932535725939'
lifecycle_stage: active
run_id: fe8e0f775efc4c9aabd5f845424d3061
run_name: handsome-mole-653
run_uuid: fe8e0f775efc4c9aabd5f845424d3061
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980115253
status: 3
tags: []
user_id: remicazelles
