artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/d286ed49067c40c18ed008da6e21187f/artifacts
end_time: 1742389500321
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: d286ed49067c40c18ed008da6e21187f
run_name: CV_elastincnet
run_uuid: d286ed49067c40c18ed008da6e21187f
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389500306
status: 3
tags: []
user_id: remicazelles
