artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/a7cf91888e8c4d3b86a3f1f7dd539bfa/artifacts
end_time: 1742389665738
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: a7cf91888e8c4d3b86a3f1f7dd539bfa
run_name: CV_elastincnet
run_uuid: a7cf91888e8c4d3b86a3f1f7dd539bfa
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389665721
status: 3
tags: []
user_id: remicazelles
