artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/f70c1e6496eb4055961cfe77b42d9dc3/artifacts
end_time: 1742980278807
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: f70c1e6496eb4055961cfe77b42d9dc3
run_name: CV_elastincnet
run_uuid: f70c1e6496eb4055961cfe77b42d9dc3
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980278789
status: 3
tags: []
user_id: remicazelles
