artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070/e6da586e91db41dd8b12daf21e81ab2f/artifacts
end_time: 1746454406808
entry_point_name: ''
experiment_id: '341922289666668070'
lifecycle_stage: active
run_id: e6da586e91db41dd8b12daf21e81ab2f
run_name: bouncy-cub-183
run_uuid: e6da586e91db41dd8b12daf21e81ab2f
source_name: ''
source_type: 4
source_version: ''
start_time: 1746454406664
status: 3
tags: []
user_id: remicazelles
