artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/04bff3b7fc014cfe9a479cbae6732659/artifacts
end_time: 1742980282400
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 04bff3b7fc014cfe9a479cbae6732659
run_name: CV_elastincnet
run_uuid: 04bff3b7fc014cfe9a479cbae6732659
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980282382
status: 3
tags: []
user_id: remicazelles
