artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/7ab8576fd87b4e74ad20a26c8f89da9d/artifacts
end_time: 1742980285213
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 7ab8576fd87b4e74ad20a26c8f89da9d
run_name: CV_elastincnet
run_uuid: 7ab8576fd87b4e74ad20a26c8f89da9d
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980285194
status: 3
tags: []
user_id: remicazelles
