artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/91c2ab50eea24801abb9dcf13aff9bbd/artifacts
end_time: 1742389665144
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 91c2ab50eea24801abb9dcf13aff9bbd
run_name: CV_elastincnet
run_uuid: 91c2ab50eea24801abb9dcf13aff9bbd
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389665127
status: 3
tags: []
user_id: remicazelles
