artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/4bc76333ffa54c5ba0fd6d75d4dedc0e/artifacts
end_time: 1742389661441
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 4bc76333ffa54c5ba0fd6d75d4dedc0e
run_name: CV_elastincnet
run_uuid: 4bc76333ffa54c5ba0fd6d75d4dedc0e
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389661425
status: 3
tags: []
user_id: remicazelles
