artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/bff0513acd9549f387a0480a3952c73b/artifacts
end_time: 1742389661176
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: bff0513acd9549f387a0480a3952c73b
run_name: CV_elastincnet
run_uuid: bff0513acd9549f387a0480a3952c73b
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389661159
status: 3
tags: []
user_id: remicazelles
