artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/380618932535725939/d89f72ca2fcb4cd88e34c5d39dcc2505/artifacts
end_time: 1742980118568
entry_point_name: ''
experiment_id: '380618932535725939'
lifecycle_stage: active
run_id: d89f72ca2fcb4cd88e34c5d39dcc2505
run_name: secretive-shark-671
run_uuid: d89f72ca2fcb4cd88e34c5d39dcc2505
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980118246
status: 3
tags: []
user_id: remicazelles
