artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/517828280626744178/01f7ae67945f43e59522fd7bee7e9ad7/artifacts
end_time: 1742388898645
entry_point_name: ''
experiment_id: '517828280626744178'
lifecycle_stage: active
run_id: 01f7ae67945f43e59522fd7bee7e9ad7
run_name: marvelous-bird-474
run_uuid: 01f7ae67945f43e59522fd7bee7e9ad7
source_name: ''
source_type: 4
source_version: ''
start_time: 1742388898559
status: 3
tags: []
user_id: remicazelles
