artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/403e2f7ac3dd44f5ada1cbc8f3b17c88/artifacts
end_time: 1742031705895
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: 403e2f7ac3dd44f5ada1cbc8f3b17c88
run_name: CV_elastincnet
run_uuid: 403e2f7ac3dd44f5ada1cbc8f3b17c88
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031705882
status: 3
tags: []
user_id: remicazelles
