artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/3fa36e28964c4fa3a203e5eee71d5d5c/artifacts
end_time: 1742980279220
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 3fa36e28964c4fa3a203e5eee71d5d5c
run_name: CV_elastincnet
run_uuid: 3fa36e28964c4fa3a203e5eee71d5d5c
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980279204
status: 3
tags: []
user_id: remicazelles
