artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070/e0783b4fefc648d394228fc0cbcbf814/artifacts
end_time: 1746454407758
entry_point_name: ''
experiment_id: '341922289666668070'
lifecycle_stage: active
run_id: e0783b4fefc648d394228fc0cbcbf814
run_name: fun-eel-673
run_uuid: e0783b4fefc648d394228fc0cbcbf814
source_name: ''
source_type: 4
source_version: ''
start_time: 1746454407590
status: 3
tags: []
user_id: remicazelles
