artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/c74b13d94fd042589f5c441bf3b142df/artifacts
end_time: 1742389500192
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: c74b13d94fd042589f5c441bf3b142df
run_name: CV_elastincnet
run_uuid: c74b13d94fd042589f5c441bf3b142df
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389500177
status: 3
tags: []
user_id: remicazelles
