artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/cc83a25787ca4e39ab4b5b5373cebaf7/artifacts
end_time: 1742389662579
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: cc83a25787ca4e39ab4b5b5373cebaf7
run_name: CV_elastincnet
run_uuid: cc83a25787ca4e39ab4b5b5373cebaf7
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389662563
status: 3
tags: []
user_id: remicazelles
