artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070/429b428ffc7b4f9ebfb482ad3a889871/artifacts
end_time: 1746454408159
entry_point_name: ''
experiment_id: '341922289666668070'
lifecycle_stage: active
run_id: 429b428ffc7b4f9ebfb482ad3a889871
run_name: sneaky-goose-602
run_uuid: 429b428ffc7b4f9ebfb482ad3a889871
source_name: ''
source_type: 4
source_version: ''
start_time: 1746454407773
status: 3
tags: []
user_id: remicazelles
