artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/8ead6bb2723f48cd85c776ab0bfe2f7e/artifacts
end_time: 1742980283937
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 8ead6bb2723f48cd85c776ab0bfe2f7e
run_name: CV_elastincnet
run_uuid: 8ead6bb2723f48cd85c776ab0bfe2f7e
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980283920
status: 3
tags: []
user_id: remicazelles
