artifact_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/161233834943891904
creation_time: 1742389500850
experiment_id: '161233834943891904'
last_update_time: 1742389500850
lifecycle_stage: active
name: /2025-03-19_Tune_model_and_log
