artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/617ab5e7acef42dc90d31cf26e23e542/artifacts
end_time: 1742980282722
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 617ab5e7acef42dc90d31cf26e23e542
run_name: CV_elastincnet
run_uuid: 617ab5e7acef42dc90d31cf26e23e542
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980282705
status: 3
tags: []
user_id: remicazelles
