artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/23c38bc9b06343eda7fbfb457d18107f/artifacts
end_time: 1742389500475
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 23c38bc9b06343eda7fbfb457d18107f
run_name: CV_elastincnet
run_uuid: 23c38bc9b06343eda7fbfb457d18107f
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389500458
status: 3
tags: []
user_id: remicazelles
