artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/6e34494ddeb64e199411b294ed9fdfab/artifacts
end_time: 1742980280781
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 6e34494ddeb64e199411b294ed9fdfab
run_name: CV_elastincnet
run_uuid: 6e34494ddeb64e199411b294ed9fdfab
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980280765
status: 3
tags: []
user_id: remicazelles
