artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/f8039fe7f0d64cc6b116803db6887d3b/artifacts
end_time: 1742980282896
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: f8039fe7f0d64cc6b116803db6887d3b
run_name: CV_elastincnet
run_uuid: f8039fe7f0d64cc6b116803db6887d3b
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980282806
status: 3
tags: []
user_id: remicazelles
