artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/517828280626744178/2170987e72594232adffbcef14fac596/artifacts
end_time: 1742388902459
entry_point_name: ''
experiment_id: '517828280626744178'
lifecycle_stage: active
run_id: 2170987e72594232adffbcef14fac596
run_name: vaunted-hawk-704
run_uuid: 2170987e72594232adffbcef14fac596
source_name: ''
source_type: 4
source_version: ''
start_time: 1742388902272
status: 3
tags: []
user_id: remicazelles
