artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/ae15bcdfa3a8457c871fb5d11fca0a6f/artifacts
end_time: 1742980283752
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: ae15bcdfa3a8457c871fb5d11fca0a6f
run_name: CV_elastincnet
run_uuid: ae15bcdfa3a8457c871fb5d11fca0a6f
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980283731
status: 3
tags: []
user_id: remicazelles
