artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/d8b18324ef4e408bab4e3aed9ea03d43/artifacts
end_time: 1742032134065
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: d8b18324ef4e408bab4e3aed9ea03d43
run_name: CV_elastincnet
run_uuid: d8b18324ef4e408bab4e3aed9ea03d43
source_name: ''
source_type: 4
source_version: ''
start_time: 1742032134049
status: 3
tags: []
user_id: remicazelles
