artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/55fd01dda21b41cc96a819df6f61f042/artifacts
end_time: 1742389663587
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 55fd01dda21b41cc96a819df6f61f042
run_name: CV_elastincnet
run_uuid: 55fd01dda21b41cc96a819df6f61f042
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389663570
status: 3
tags: []
user_id: remicazelles
