artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/d959b0d0c6c1422a82c29d64a9e5d09b/artifacts
end_time: 1742389662776
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: d959b0d0c6c1422a82c29d64a9e5d09b
run_name: CV_elastincnet
run_uuid: d959b0d0c6c1422a82c29d64a9e5d09b
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389662758
status: 3
tags: []
user_id: remicazelles
