artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/f3a5a3f0a5b044d38d40befff25c662c/artifacts
end_time: 1742389660872
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: f3a5a3f0a5b044d38d40befff25c662c
run_name: CV_elastincnet
run_uuid: f3a5a3f0a5b044d38d40befff25c662c
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389660853
status: 3
tags: []
user_id: remicazelles
