artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/380618932535725939/6ce163f604844041bcdb13131ebfbd88/artifacts
end_time: 1742980115231
entry_point_name: ''
experiment_id: '380618932535725939'
lifecycle_stage: active
run_id: 6ce163f604844041bcdb13131ebfbd88
run_name: dazzling-snipe-127
run_uuid: 6ce163f604844041bcdb13131ebfbd88
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980115111
status: 3
tags: []
user_id: remicazelles
