artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/1047366ae7e14c64abf109dd6ef456f2/artifacts
end_time: 1742980280429
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 1047366ae7e14c64abf109dd6ef456f2
run_name: CV_elastincnet
run_uuid: 1047366ae7e14c64abf109dd6ef456f2
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980280412
status: 3
tags: []
user_id: remicazelles
