artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/622210678106996608/95a38fb9cce34fcbbb01bf66832fa1a5/artifacts
end_time: 1742031655800
entry_point_name: ''
experiment_id: '622210678106996608'
lifecycle_stage: active
run_id: 95a38fb9cce34fcbbb01bf66832fa1a5
run_name: 2025-03-15_elasticnet_best_model_run
run_uuid: 95a38fb9cce34fcbbb01bf66832fa1a5
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031653260
status: 3
tags: []
user_id: remicazelles
