artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/a5cf9889c67c421a987cd5d979c7c80b/artifacts
end_time: 1742389500257
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: a5cf9889c67c421a987cd5d979c7c80b
run_name: CV_elastincnet
run_uuid: a5cf9889c67c421a987cd5d979c7c80b
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389500243
status: 3
tags: []
user_id: remicazelles
