artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/7fefcb7ef8c9439394faf125fe654efb/artifacts
end_time: 1742980281086
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 7fefcb7ef8c9439394faf125fe654efb
run_name: CV_elastincnet
run_uuid: 7fefcb7ef8c9439394faf125fe654efb
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980281069
status: 3
tags: []
user_id: remicazelles
