artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/0a10a4ff45f14a1c839314c51b261c0b/artifacts
end_time: 1742980281726
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 0a10a4ff45f14a1c839314c51b261c0b
run_name: CV_elastincnet
run_uuid: 0a10a4ff45f14a1c839314c51b261c0b
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980281709
status: 3
tags: []
user_id: remicazelles
