artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/79169fdc657b4681a5f255c50bf4a6b4/artifacts
end_time: 1742389663864
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 79169fdc657b4681a5f255c50bf4a6b4
run_name: CV_elastincnet
run_uuid: 79169fdc657b4681a5f255c50bf4a6b4
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389663847
status: 3
tags: []
user_id: remicazelles
