artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/df6ebd4950a341ac95f60eaf8066dff7/artifacts
end_time: 1742031705593
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: df6ebd4950a341ac95f60eaf8066dff7
run_name: CV_elastincnet
run_uuid: df6ebd4950a341ac95f60eaf8066dff7
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031705580
status: 3
tags: []
user_id: remicazelles
