artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/1add52e78fab487ca6180ff71785ef8e/artifacts
end_time: 1742980284641
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 1add52e78fab487ca6180ff71785ef8e
run_name: CV_elastincnet
run_uuid: 1add52e78fab487ca6180ff71785ef8e
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980284622
status: 3
tags: []
user_id: remicazelles
