artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/d7cd1cf7b4b6474cb02306184e1c4972/artifacts
end_time: 1742389666534
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: d7cd1cf7b4b6474cb02306184e1c4972
run_name: CV_elastincnet
run_uuid: d7cd1cf7b4b6474cb02306184e1c4972
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389666517
status: 3
tags: []
user_id: remicazelles
