artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/eb6050c8b9e14203ada32df4016e8186/artifacts
end_time: 1742389499945
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: eb6050c8b9e14203ada32df4016e8186
run_name: CV_elastincnet
run_uuid: eb6050c8b9e14203ada32df4016e8186
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389499927
status: 3
tags: []
user_id: remicazelles
