artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/acd80676e2264032a94bfa093f6ce1ef/artifacts
end_time: 1742980282504
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: acd80676e2264032a94bfa093f6ce1ef
run_name: CV_elastincnet
run_uuid: acd80676e2264032a94bfa093f6ce1ef
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980282486
status: 3
tags: []
user_id: remicazelles
