artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/d64f5ea1121745afabe3a0cb81084b37/artifacts
end_time: 1742032545675
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: d64f5ea1121745afabe3a0cb81084b37
run_name: CV_elastincnet
run_uuid: d64f5ea1121745afabe3a0cb81084b37
source_name: ''
source_type: 4
source_version: ''
start_time: 1742032545661
status: 3
tags: []
user_id: remicazelles
