artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/c721439ea59e424ab8be4a65c832b263/artifacts
end_time: 1742980284292
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: c721439ea59e424ab8be4a65c832b263
run_name: CV_elastincnet
run_uuid: c721439ea59e424ab8be4a65c832b263
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980284274
status: 3
tags: []
user_id: remicazelles
