artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/9985d63eda4b4e578f9f5372f5eb27d0/artifacts
end_time: 1742389664681
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 9985d63eda4b4e578f9f5372f5eb27d0
run_name: CV_elastincnet
run_uuid: 9985d63eda4b4e578f9f5372f5eb27d0
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389664665
status: 3
tags: []
user_id: remicazelles
