artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/b6ca37b7ce4f4e75b26fdba0195335b1/artifacts
end_time: 1742389662042
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: b6ca37b7ce4f4e75b26fdba0195335b1
run_name: CV_elastincnet
run_uuid: b6ca37b7ce4f4e75b26fdba0195335b1
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389662025
status: 3
tags: []
user_id: remicazelles
