artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/161233834943891904/4cb4bf4042cb44698b76b8afa248b422/artifacts
end_time: 1742389504028
entry_point_name: ''
experiment_id: '161233834943891904'
lifecycle_stage: active
run_id: 4cb4bf4042cb44698b76b8afa248b422
run_name: 2025-03-19_elasticnet_best_model_run
run_uuid: 4cb4bf4042cb44698b76b8afa248b422
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389500963
status: 3
tags: []
user_id: remicazelles
