artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/42bd7e19d73d42cdbb7be91d489377c8/artifacts
end_time: 1742980280038
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 42bd7e19d73d42cdbb7be91d489377c8
run_name: CV_elastincnet
run_uuid: 42bd7e19d73d42cdbb7be91d489377c8
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980280021
status: 3
tags: []
user_id: remicazelles
