artifact_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/485845010693164534
creation_time: 1742980286718
experiment_id: '485845010693164534'
last_update_time: 1742980286718
lifecycle_stage: active
name: /2025-03-26_Tune_model_and_log
