artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/a2300794fdb74d2aa6d1ab5f141535ea/artifacts
end_time: 1742389666563
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: a2300794fdb74d2aa6d1ab5f141535ea
run_name: CV_elastincnet
run_uuid: a2300794fdb74d2aa6d1ab5f141535ea
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389666542
status: 3
tags: []
user_id: remicazelles
