artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/82b1df2767f74f82b67e882c575dac81/artifacts
end_time: 1742389660706
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 82b1df2767f74f82b67e882c575dac81
run_name: CV_elastincnet
run_uuid: 82b1df2767f74f82b67e882c575dac81
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389660691
status: 3
tags: []
user_id: remicazelles
