artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/10afc5d9bfdd4078a41640e3c859d1ca/artifacts
end_time: 1742980277898
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 10afc5d9bfdd4078a41640e3c859d1ca
run_name: CV_elastincnet
run_uuid: 10afc5d9bfdd4078a41640e3c859d1ca
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980277882
status: 3
tags: []
user_id: remicazelles
