artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/0/da3258d8dba64d4aa30b02e36319da0c/artifacts
end_time: 1742993160868
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: da3258d8dba64d4aa30b02e36319da0c
run_name: 2025-03-26_elasticnet_best_model_run
run_uuid: da3258d8dba64d4aa30b02e36319da0c
source_name: ''
source_type: 4
source_version: ''
start_time: 1742993157927
status: 3
tags: []
user_id: remicazelles
