artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/58a28dd65f644577bb8e8719d31ebe48/artifacts
end_time: 1742980284506
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 58a28dd65f644577bb8e8719d31ebe48
run_name: CV_elastincnet
run_uuid: 58a28dd65f644577bb8e8719d31ebe48
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980284486
status: 3
tags: []
user_id: remicazelles
