artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/380618932535725939/9a7d83b5208a4f6aaa746c7952bcb30c/artifacts
end_time: 1742980117233
entry_point_name: ''
experiment_id: '380618932535725939'
lifecycle_stage: active
run_id: 9a7d83b5208a4f6aaa746c7952bcb30c
run_name: peaceful-snail-482
run_uuid: 9a7d83b5208a4f6aaa746c7952bcb30c
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980117174
status: 3
tags: []
user_id: remicazelles
