artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/b978c466c04348ffa63de1cc921cba08/artifacts
end_time: 1742032545505
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: b978c466c04348ffa63de1cc921cba08
run_name: CV_elastincnet
run_uuid: b978c466c04348ffa63de1cc921cba08
source_name: ''
source_type: 4
source_version: ''
start_time: 1742032545492
status: 3
tags: []
user_id: remicazelles
