artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/1093e3441afc46a6b5cb39d5d4a1eecc/artifacts
end_time: 1742389665065
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 1093e3441afc46a6b5cb39d5d4a1eecc
run_name: CV_elastincnet
run_uuid: 1093e3441afc46a6b5cb39d5d4a1eecc
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389665044
status: 3
tags: []
user_id: remicazelles
