artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/afad5bf75db8461ca7b2314655d62713/artifacts
end_time: 1742389663114
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: afad5bf75db8461ca7b2314655d62713
run_name: CV_elastincnet
run_uuid: afad5bf75db8461ca7b2314655d62713
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389663098
status: 3
tags: []
user_id: remicazelles
