artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/b885d290c8ca48f98294229d8bce49b8/artifacts
end_time: 1742980284182
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: b885d290c8ca48f98294229d8bce49b8
run_name: CV_elastincnet
run_uuid: b885d290c8ca48f98294229d8bce49b8
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980284165
status: 3
tags: []
user_id: remicazelles
