artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/a5f25f7671114f50a51183d9ebc2a91f/artifacts
end_time: 1742389661394
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: a5f25f7671114f50a51183d9ebc2a91f
run_name: CV_elastincnet
run_uuid: a5f25f7671114f50a51183d9ebc2a91f
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389661378
status: 3
tags: []
user_id: remicazelles
