artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/3fe8e4348b384853a85f52d0436ca4ce/artifacts
end_time: 1742980281675
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 3fe8e4348b384853a85f52d0436ca4ce
run_name: CV_elastincnet
run_uuid: 3fe8e4348b384853a85f52d0436ca4ce
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980281658
status: 3
tags: []
user_id: remicazelles
