artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/c71331d5273143fa8c106405fcbc18ff/artifacts
end_time: 1742389500236
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: c71331d5273143fa8c106405fcbc18ff
run_name: CV_elastincnet
run_uuid: c71331d5273143fa8c106405fcbc18ff
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389500222
status: 3
tags: []
user_id: remicazelles
