artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/dab03653edfe43ba8178637a29e2058f/artifacts
end_time: 1742032545263
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: dab03653edfe43ba8178637a29e2058f
run_name: CV_elastincnet
run_uuid: dab03653edfe43ba8178637a29e2058f
source_name: ''
source_type: 4
source_version: ''
start_time: 1742032545247
status: 3
tags: []
user_id: remicazelles
