artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/ba773a82efe642d89170554efbbc4d59/artifacts
end_time: 1742980280137
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: ba773a82efe642d89170554efbbc4d59
run_name: CV_elastincnet
run_uuid: ba773a82efe642d89170554efbbc4d59
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980280120
status: 3
tags: []
user_id: remicazelles
