artifact_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727
creation_time: 1742031651822
experiment_id: '345960583960283727'
last_update_time: 1742031651822
lifecycle_stage: active
name: 2025-03-15_ElasticNetCV_hyperparams_search
