artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/6bff60a01e2b40fe8d8db5d18aeb1d9a/artifacts
end_time: 1742389663384
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 6bff60a01e2b40fe8d8db5d18aeb1d9a
run_name: CV_elastincnet
run_uuid: 6bff60a01e2b40fe8d8db5d18aeb1d9a
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389663366
status: 3
tags: []
user_id: remicazelles
