artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/a4bdfb6fd7b142bba159dd758423b277/artifacts
end_time: 1742980277739
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: a4bdfb6fd7b142bba159dd758423b277
run_name: CV_elastincnet
run_uuid: a4bdfb6fd7b142bba159dd758423b277
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980277706
status: 3
tags: []
user_id: remicazelles
