artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070/2e24e680eeb14494b717ada30c3b54c3/artifacts
end_time: 1746454407317
entry_point_name: ''
experiment_id: '341922289666668070'
lifecycle_stage: active
run_id: 2e24e680eeb14494b717ada30c3b54c3
run_name: lyrical-bee-198
run_uuid: 2e24e680eeb14494b717ada30c3b54c3
source_name: ''
source_type: 4
source_version: ''
start_time: 1746454407240
status: 3
tags: []
user_id: remicazelles
