artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/7b12c16b4bdb4bd4972e9146d8ca30c9/artifacts
end_time: 1742031705504
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: 7b12c16b4bdb4bd4972e9146d8ca30c9
run_name: CV_elastincnet
run_uuid: 7b12c16b4bdb4bd4972e9146d8ca30c9
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031705491
status: 3
tags: []
user_id: remicazelles
