artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/60e61e6b4f8b485fa3fce6263523f577/artifacts
end_time: 1742980277922
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 60e61e6b4f8b485fa3fce6263523f577
run_name: CV_elastincnet
run_uuid: 60e61e6b4f8b485fa3fce6263523f577
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980277906
status: 3
tags: []
user_id: remicazelles
