artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/bb82aed20e5d4890b87cae42421797b7/artifacts
end_time: 1742031705729
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: bb82aed20e5d4890b87cae42421797b7
run_name: CV_elastincnet
run_uuid: bb82aed20e5d4890b87cae42421797b7
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031705716
status: 3
tags: []
user_id: remicazelles
