artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/517828280626744178/822fe19c99ea456a930ec0d7ae56c48f/artifacts
end_time: 1742388902646
entry_point_name: ''
experiment_id: '517828280626744178'
lifecycle_stage: active
run_id: 822fe19c99ea456a930ec0d7ae56c48f
run_name: brawny-stag-809
run_uuid: 822fe19c99ea456a930ec0d7ae56c48f
source_name: ''
source_type: 4
source_version: ''
start_time: 1742388902467
status: 3
tags: []
user_id: remicazelles
