artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/8f99544c1e5e459b9eb07e28f3cdb3ae/artifacts
end_time: 1742389665662
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 8f99544c1e5e459b9eb07e28f3cdb3ae
run_name: CV_elastincnet
run_uuid: 8f99544c1e5e459b9eb07e28f3cdb3ae
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389665645
status: 3
tags: []
user_id: remicazelles
