artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/2d72e665d7854dc9bd216fc7a545a231/artifacts
end_time: 1742980277874
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 2d72e665d7854dc9bd216fc7a545a231
run_name: CV_elastincnet
run_uuid: 2d72e665d7854dc9bd216fc7a545a231
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980277859
status: 3
tags: []
user_id: remicazelles
