artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/fd08fea5902642fa827fefd6f2bfd207/artifacts
end_time: 1742031705661
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: fd08fea5902642fa827fefd6f2bfd207
run_name: CV_elastincnet
run_uuid: fd08fea5902642fa827fefd6f2bfd207
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031705649
status: 3
tags: []
user_id: remicazelles
