artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/74c662dd01a546a0aea68ac457271cde/artifacts
end_time: 1742980282747
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 74c662dd01a546a0aea68ac457271cde
run_name: CV_elastincnet
run_uuid: 74c662dd01a546a0aea68ac457271cde
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980282730
status: 3
tags: []
user_id: remicazelles
