artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/0/dd6f703f7814496da5b615e1a1762d3c/artifacts
end_time: 1742987060391
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: dd6f703f7814496da5b615e1a1762d3c
run_name: CrossValidate_elasticnet
run_uuid: dd6f703f7814496da5b615e1a1762d3c
source_name: ''
source_type: 4
source_version: ''
start_time: 1742987060242
status: 3
tags: []
user_id: remicazelles
