artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/b47c91a5fd9e40d8bec423cc96073d3e/artifacts
end_time: 1742980280855
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: b47c91a5fd9e40d8bec423cc96073d3e
run_name: CV_elastincnet
run_uuid: b47c91a5fd9e40d8bec423cc96073d3e
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980280838
status: 3
tags: []
user_id: remicazelles
