artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/0/f940c84bb34649bdbe489ae1717818df/artifacts
end_time: 1742996448842
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f940c84bb34649bdbe489ae1717818df
run_name: 2025-03-26_elasticnet_best_model_run
run_uuid: f940c84bb34649bdbe489ae1717818df
source_name: ''
source_type: 4
source_version: ''
start_time: 1742996446065
status: 3
tags: []
user_id: remicazelles
