artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/485845010693164534/e005992290ad4310b6c44d22feea56d8/artifacts
end_time: 1742980286818
entry_point_name: ''
experiment_id: '485845010693164534'
lifecycle_stage: active
run_id: e005992290ad4310b6c44d22feea56d8
run_name: CrossValidate_elasticnet
run_uuid: e005992290ad4310b6c44d22feea56d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980286722
status: 3
tags: []
user_id: remicazelles
