artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/1c7e8a8e84e0479d8e0fc18776ad3266/artifacts
end_time: 1742389666272
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 1c7e8a8e84e0479d8e0fc18776ad3266
run_name: CV_elastincnet
run_uuid: 1c7e8a8e84e0479d8e0fc18776ad3266
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389666254
status: 3
tags: []
user_id: remicazelles
