artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/622210678106996608/80922710e58140faadce94a0e9a712f5/artifacts
end_time: 1742031653251
entry_point_name: ''
experiment_id: '622210678106996608'
lifecycle_stage: active
run_id: 80922710e58140faadce94a0e9a712f5
run_name: CrossValidate_elasticnet
run_uuid: 80922710e58140faadce94a0e9a712f5
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031653157
status: 3
tags: []
user_id: remicazelles
