artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/0edae95db6c545ac8a1d0e815c95415c/artifacts
end_time: 1742389658984
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 0edae95db6c545ac8a1d0e815c95415c
run_name: CV_elastincnet
run_uuid: 0edae95db6c545ac8a1d0e815c95415c
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389658969
status: 3
tags: []
user_id: remicazelles
