artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/380618932535725939/3ae0f337008642b59bd13a3a74de963b/artifacts
end_time: 1742980115671
entry_point_name: ''
experiment_id: '380618932535725939'
lifecycle_stage: active
run_id: 3ae0f337008642b59bd13a3a74de963b
run_name: masked-sloth-22
run_uuid: 3ae0f337008642b59bd13a3a74de963b
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980115609
status: 3
tags: []
user_id: remicazelles
