artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/517828280626744178/036a5b682baa4cbaa92c9be477aed3a2/artifacts
end_time: 1742388899202
entry_point_name: ''
experiment_id: '517828280626744178'
lifecycle_stage: active
run_id: 036a5b682baa4cbaa92c9be477aed3a2
run_name: stylish-gnat-717
run_uuid: 036a5b682baa4cbaa92c9be477aed3a2
source_name: ''
source_type: 4
source_version: ''
start_time: 1742388898852
status: 3
tags: []
user_id: remicazelles
