artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/1f288a968df34561b6451f8fea81ceef/artifacts
end_time: 1742980283140
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 1f288a968df34561b6451f8fea81ceef
run_name: CV_elastincnet
run_uuid: 1f288a968df34561b6451f8fea81ceef
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980283122
status: 3
tags: []
user_id: remicazelles
