artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/517828280626744178/ea2206b9ef5f4d528a585e60f2bc6c94/artifacts
end_time: 1742388903174
entry_point_name: ''
experiment_id: '517828280626744178'
lifecycle_stage: active
run_id: ea2206b9ef5f4d528a585e60f2bc6c94
run_name: able-doe-626
run_uuid: ea2206b9ef5f4d528a585e60f2bc6c94
source_name: ''
source_type: 4
source_version: ''
start_time: 1742388898038
status: 3
tags: []
user_id: remicazelles
