artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070/8eb7a1ad0a724dbbb03cac880b149a1a/artifacts
end_time: 1746454408270
entry_point_name: ''
experiment_id: '341922289666668070'
lifecycle_stage: active
run_id: 8eb7a1ad0a724dbbb03cac880b149a1a
run_name: youthful-snake-705
run_uuid: 8eb7a1ad0a724dbbb03cac880b149a1a
source_name: ''
source_type: 4
source_version: ''
start_time: 1746454408173
status: 3
tags: []
user_id: remicazelles
