artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/8a3ed83b1e9241418b3b00582fdc338b/artifacts
end_time: 1742389666117
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 8a3ed83b1e9241418b3b00582fdc338b
run_name: CV_elastincnet
run_uuid: 8a3ed83b1e9241418b3b00582fdc338b
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389666098
status: 3
tags: []
user_id: remicazelles
