artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/075f77a72e8d4fc798c99bafe350016d/artifacts
end_time: 1742389660316
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 075f77a72e8d4fc798c99bafe350016d
run_name: CV_elastincnet
run_uuid: 075f77a72e8d4fc798c99bafe350016d
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389660228
status: 3
tags: []
user_id: remicazelles
