artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/d3b49aa7cb034351a5f5e194c002c449/artifacts
end_time: 1742389663915
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: d3b49aa7cb034351a5f5e194c002c449
run_name: CV_elastincnet
run_uuid: d3b49aa7cb034351a5f5e194c002c449
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389663897
status: 3
tags: []
user_id: remicazelles
