artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/840893b6b0614f90bbf30ee53ac30ce0/artifacts
end_time: 1742980283114
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 840893b6b0614f90bbf30ee53ac30ce0
run_name: CV_elastincnet
run_uuid: 840893b6b0614f90bbf30ee53ac30ce0
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980283097
status: 3
tags: []
user_id: remicazelles
