artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/a071a9ea7cd44dd9bda3e8bc653fd767/artifacts
end_time: 1742389500029
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: a071a9ea7cd44dd9bda3e8bc653fd767
run_name: CV_elastincnet
run_uuid: a071a9ea7cd44dd9bda3e8bc653fd767
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389500011
status: 3
tags: []
user_id: remicazelles
