artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/345960583960283727/3cebfdd2a0aa442eb9ddfcc15312171c/artifacts
end_time: 1742031705811
entry_point_name: ''
experiment_id: '345960583960283727'
lifecycle_stage: active
run_id: 3cebfdd2a0aa442eb9ddfcc15312171c
run_name: CV_elastincnet
run_uuid: 3cebfdd2a0aa442eb9ddfcc15312171c
source_name: ''
source_type: 4
source_version: ''
start_time: 1742031705798
status: 3
tags: []
user_id: remicazelles
