artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/517828280626744178/1b45d3312c2143e6b45a0a22a760caab/artifacts
end_time: 1742388903150
entry_point_name: ''
experiment_id: '517828280626744178'
lifecycle_stage: active
run_id: 1b45d3312c2143e6b45a0a22a760caab
run_name: blushing-newt-261
run_uuid: 1b45d3312c2143e6b45a0a22a760caab
source_name: ''
source_type: 4
source_version: ''
start_time: 1742388902802
status: 3
tags: []
user_id: remicazelles
