aliases: []
creation_timestamp: 1742996130346
current_stage: None
description: ''
last_updated_timestamp: 1742996130346
name: best_elasticnet_model_on_2025-03-26
run_id: b55185ee1bd04934999097be1fadfa17
run_link: ''
source: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/0/b55185ee1bd04934999097be1fadfa17/artifacts/logged_model
status: READY
status_message: null
storage_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/ML_supervized/artifacts_RC/0/b55185ee1bd04934999097be1fadfa17/artifacts/logged_model
user_id: null
version: 8
