artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/517828280626744178/3f4c8ae8b9714a05b4e6778aecac900b/artifacts
end_time: 1742388900651
entry_point_name: ''
experiment_id: '517828280626744178'
lifecycle_stage: active
run_id: 3f4c8ae8b9714a05b4e6778aecac900b
run_name: merciful-duck-8
run_uuid: 3f4c8ae8b9714a05b4e6778aecac900b
source_name: ''
source_type: 4
source_version: ''
start_time: 1742388900497
status: 3
tags: []
user_id: remicazelles
