artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/2db97aff8c3e4552bcaa4c984b97f3ab/artifacts
end_time: 1742389661106
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 2db97aff8c3e4552bcaa4c984b97f3ab
run_name: CV_elastincnet
run_uuid: 2db97aff8c3e4552bcaa4c984b97f3ab
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389661091
status: 3
tags: []
user_id: remicazelles
