artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/1dd8946fc3bf41a7b42718750f2b50f1/artifacts
end_time: 1742980283454
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: 1dd8946fc3bf41a7b42718750f2b50f1
run_name: CV_elastincnet
run_uuid: 1dd8946fc3bf41a7b42718750f2b50f1
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980283436
status: 3
tags: []
user_id: remicazelles
