artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/fe09d7944fb947dfa12cfe4c2114597d/artifacts
end_time: 1742389660513
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: fe09d7944fb947dfa12cfe4c2114597d
run_name: CV_elastincnet
run_uuid: fe09d7944fb947dfa12cfe4c2114597d
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389660497
status: 3
tags: []
user_id: remicazelles
