artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/4bcf0ffd2ef94a788936fdfdd3f22779/artifacts
end_time: 1742389660003
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 4bcf0ffd2ef94a788936fdfdd3f22779
run_name: CV_elastincnet
run_uuid: 4bcf0ffd2ef94a788936fdfdd3f22779
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389659985
status: 3
tags: []
user_id: remicazelles
