artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/abcc3a2989584bfebbc7b1d9b6a2022e/artifacts
end_time: 1742980285044
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: abcc3a2989584bfebbc7b1d9b6a2022e
run_name: CV_elastincnet
run_uuid: abcc3a2989584bfebbc7b1d9b6a2022e
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980285025
status: 3
tags: []
user_id: remicazelles
