artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/59a973536ff34d3cbcfa64147cd2ec05/artifacts
end_time: 1742389666171
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 59a973536ff34d3cbcfa64147cd2ec05
run_name: CV_elastincnet
run_uuid: 59a973536ff34d3cbcfa64147cd2ec05
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389666153
status: 3
tags: []
user_id: remicazelles
