artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/380618932535725939/222ad8b98acd4fad9457e55bfa0044b8/artifacts
end_time: 1742980118064
entry_point_name: ''
experiment_id: '380618932535725939'
lifecycle_stage: active
run_id: 222ad8b98acd4fad9457e55bfa0044b8
run_name: dazzling-cod-727
run_uuid: 222ad8b98acd4fad9457e55bfa0044b8
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980117952
status: 3
tags: []
user_id: remicazelles
