artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/b46d65e48d1b4cf793a448f8b2aff6a4/artifacts
end_time: 1742389660393
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: b46d65e48d1b4cf793a448f8b2aff6a4
run_name: CV_elastincnet
run_uuid: b46d65e48d1b4cf793a448f8b2aff6a4
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389660372
status: 3
tags: []
user_id: remicazelles
