artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/351470198043080846/46afa4c6143542f99036a2cde571ba4d/artifacts
end_time: 1742389660777
entry_point_name: ''
experiment_id: '351470198043080846'
lifecycle_stage: active
run_id: 46afa4c6143542f99036a2cde571ba4d
run_name: CV_elastincnet
run_uuid: 46afa4c6143542f99036a2cde571ba4d
source_name: ''
source_type: 4
source_version: ''
start_time: 1742389660761
status: 3
tags: []
user_id: remicazelles
