artifact_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070
creation_time: 1746454404685
experiment_id: '341922289666668070'
last_update_time: 1746454404685
lifecycle_stage: active
name: /search_algo_2025-05-05
