artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/341922289666668070/f706ce0b21bd44b6b0bcb235e843fedb/artifacts
end_time: 1746454410421
entry_point_name: ''
experiment_id: '341922289666668070'
lifecycle_stage: active
run_id: f706ce0b21bd44b6b0bcb235e843fedb
run_name: glamorous-pig-755
run_uuid: f706ce0b21bd44b6b0bcb235e843fedb
source_name: ''
source_type: 4
source_version: ''
start_time: 1746454410342
status: 3
tags: []
user_id: remicazelles
