artifact_uri: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/740126467069218293/e744b106f9fe4bde8a54f4661fde0083/artifacts
end_time: 1742980278046
entry_point_name: ''
experiment_id: '740126467069218293'
lifecycle_stage: active
run_id: e744b106f9fe4bde8a54f4661fde0083
run_name: CV_elastincnet
run_uuid: e744b106f9fe4bde8a54f4661fde0083
source_name: ''
source_type: 4
source_version: ''
start_time: 1742980278030
status: 3
tags: []
user_id: remicazelles
