aliases: []
creation_timestamp: 1742389670043
current_stage: None
description: ''
last_updated_timestamp: 1742389670043
name: best_elasticnet_model_on_2025-03-19
run_id: d2d30a261b044997ae993b1bd22f664b
run_link: ''
source: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/161233834943891904/d2d30a261b044997ae993b1bd22f664b/artifacts/logged_model
status: READY
status_message: null
storage_location: file:///Users/remicazelles/Documents/Travail/2023-SImplon_microsoft/PROJET_FINAL/API_ML/ML_models/ML_supervized/artifacts_RC/161233834943891904/d2d30a261b044997ae993b1bd22f664b/artifacts/logged_model
user_id: null
version: 2
